version: "3"
services:
  site:
    environment:
      - IS_DOCKER=true
      - NODE_ENV=production
    image: imperative/site:0.1
    # depends_on:
    #   - blog
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/site
    networks:
      - imperativedesign

  blog:
    # environment:
      # - IS_DOCKER=${IS_DOCKER}
      # - NODE_ENV=${NODE_ENV}
      # - CLEARDB_DATABASE_URL=${CLEARDB_DATABASE_URL}
      # - database__client=${database__client}
      # - database__connection__database=${database__connection__database}
      # - database__connection__host=${database__connection__host}
      # - database__connection__password=${database__connection__password}
      # - database__connection__user=${database__connection__user}
      # - database__pool__min=${database__pool__min}
      # - database__pool__max=${database__pool__max}
      # - max_user_connections=${max_user_connections}
      # # - HEROKU_POSTGRESQL_BL  UE_URL=${HEROKU_POSTGRESQL_BLUE_URL}
      # - MANDRILL_APIKEY=${MANDRILL_APIKEY}
      # - MANDRILL_USERNAME=${MANDRILL_USERNAME}
      # - NODE_MODULES_CACHE=${NODE_MODULES_CACHE}
      # - NODE_VERBOSE=${NODE_VERBOSE}
      # - url=${url}
    image: ghost
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4200:2368"
    networks:
      - imperativedesign

  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   # volumes:
  #   #   - mysql-volume:/var/lib/mysql
  #   environment:
  #     - MYSQL_DB=heroku_d6140dbbff83350
  #     - MYSQL_HOST=us-cdbr-iron-east-05.cleardb.net
  #     - MYSQL_PASSWORD=2b55ef66ef01141
  #     - MYSQL_USER=b5d1e148a9ba84
  #     - MAX_CONNCETIONS=20
networks:
  imperativedesign:
    driver: bridge
